[package]
name = "bellman-bignat"
version = "0.1.0"

[dependencies]
rand = "0.4.5"
hex = "0.3.2"
time = "0.1"
num-bigint = "0.2"
num-traits = "0.2"

sapling-crypto = { package = "sapling-crypto_ce", version = "0.1.0" }

[dev-dependencies]
quickcheck = "0.8"
quickcheck_macros = "0.8"
color-backtrace = { version = "0.2" }
