[package]
name = "bellman-bignat"
version = "0.1.0"

[dependencies]
docopt = "1"
rand = "0.4.5"
hex = "0.3.2"
time = "0.1"
num-bigint = "0.2"
num-traits = "0.2"
num-integer = "0.1"
sapling-crypto = { package = "sapling-crypto_ce", version = "0.1.0" }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
quickcheck = "0.8"
quickcheck_macros = "0.8"
color-backtrace = { version = "0.2" }
